# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  admin.organization:
          class: App\CrocworkBundle\Admin\OrganizationAdmin
          arguments: [~, App\CrocworkBundle\Entity\Organization, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: All Tables, label: "Organizations" }
  admin.user:
            class: App\CrocworkBundle\Admin\UserAdmin
            arguments: [~, App\CrocworkBundle\Entity\User, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: All Tables, label: "Users" }
  admin.upload:
              class: App\CrocworkBundle\Admin\UploadAdmin
              arguments: [~, App\CrocworkBundle\Entity\Upload, ~]
              tags:
                  - { name: sonata.admin, manager_type: orm, group: Tools, label: "Upload Data" }