app_organization_index:
    path:     /
    defaults: { _controller: "AppCrocworkBundle:Organization:index" }
    methods:  GET

app_organization_show:
    path:     /{id}/show
    defaults: { _controller: "AppCrocworkBundle:Organization:show" }
    methods:  GET

app_organization_new:
    path:     /new
    defaults: { _controller: "AppCrocworkBundle:Organization:new" }
    methods:  [GET, POST]

app_organization_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppCrocworkBundle:Organization:edit" }
    methods:  [GET, POST]

app_organization_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppCrocworkBundle:Organization:delete" }
    methods:  DELETE
