app_user_index:
    path:     /
    defaults: { _controller: "AppCrocworkBundle:User:index" }
    methods:  GET

app_user_show:
    path:     /{id}/show
    defaults: { _controller: "AppCrocworkBundle:User:show" }
    methods:  GET

app_user_new:
    path:     /new
    defaults: { _controller: "AppCrocworkBundle:User:new" }
    methods:  [GET, POST]

app_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppCrocworkBundle:User:edit" }
    methods:  [GET, POST]

app_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppCrocworkBundle:User:delete" }
    methods:  DELETE
